In [1]:
# Initialize Otter
import otter
grader = otter.Notebook("hwk1-task2-corals.ipynb")

# Task 2: Exploring coral diversity data

## Instructions 

- First, update the following cell to have a link to *your* Homework 1 GitHub repository:

**UPDATE THIS LINK:**

[https://github.com/Karlavramos/eds220-hwk1]()

- This task covers topics on the lesson on [subsetting `pandas.DataFrames`](https://meds-eds-220.github.io/MEDS-eds-220-course/book/chapters/lesson-3-pandas-subsetting/lesson-3-pandas-subsetting.html). The best strategy to solve it is to get together with your classmates and work on it together after that lecture.

- Review the [complete rubric for this task](https://docs.google.com/document/d/131OnUDOLpOl94SlaMU9nGqT998ABrjFS/edit?usp=sharing&ouid=111507336322611936333&rtpof=true&sd=true) before starting.

- **Make at least 5 commits at moments you think are adequate.** We'll check your repository and view the commit history.

- **Add comments for all your code.** Err on the side of commenting too much for now. Comments should follow best practices.

<!-- BEGIN QUESTION -->


## 1
For this task we are going to use data about  [Western Indian Ocean Coral Diversity (McClanahan, 2023)](https://knb.ecoinformatics.org/view/doi%3A10.5063%2FF1K35S3H) from the Knowledge Network for Biocomplexity (KNB) data repository. 

a. Navigate to the dataset's link and explore the data package. 
 
b. Use the next markdown cell to add a brief description of the dataset, including a citation, date of access, and a link to the archive.

Description: 

Citation: Tim McClanahan. (2023). Western Indian Ocean Coral Diversity. Knowledge Network for Biocomplexity. doi:10.5063/F1K35S3H. 

Date of access: 09-09-2026

Link to archive: doi:10.5063/F1K35S3H

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 2
In the next code cell, import the `pandas` package using standard abbreviation in a code cell.

Read in the data from the URL using the `pd.read_csv` function and store it as `coral_div` like this:

```
# read in data
coral_div = pd.read_csv('the URL goes here')
```

In [2]:
import pandas as pd
coral_div = pd.read_csv('data/coral_data.csv')

<!-- END QUESTION -->

## 3

Use attributes and methods of the `coral_div` data frame to obtain the following information about it:

Use the code cells marked a-e. For each, add a comment explaining what is the ouput.

a. how many rows and columns does it have? Store your answers in the `rows` and `columns` variables.

In [3]:
coral_div.shape # Find the amount of rows and colums for df

(575, 42)

In [4]:
#a
rows = 575
columns = 42

In [5]:
grader.check("q3_a")

q3_a results: All test cases passed!

b. What are the column names? Store your answer in the `coral_div_columns` variable.

In [6]:
coral_div.columns # Explore columns in df

Index(['PU_ID', 'PU_Lat', 'PU_Lon', 'Number_of_genera', 'Country', 'Ecoregion',
       'Management', 'Habitat', 'Observer', 'Depth', 'Coralcover',
       'SSTRateofRise', 'PARmax', 'Calcite', 'Dis_oxygen', 'mean.waveNRJ',
       'Salinity_mean', 'andrello_reef_value', 'andrello_nutrients',
       'mean.npp', 'TT_market_hrs', 'TT_pop_hrs', 'cumDHW', 'SST_Kurtosis',
       'SST_Median', 'ChlorA_median', 'andrello_sediments', 'Current_vel_mean',
       'Diff_attenuation', 'Grav_NP', 'Grav_NC', 'PH', 'SST_bimodality',
       'SST_Skewness', 'ClimateStressModel', 'Netflow', 'Indegree',
       'Outdegree', 'Retention', 'min_yr', 'max_yr', 'no_replicates'],
      dtype='object')

In [7]:
#b
coral_div_columns = coral_div.columns

In [8]:
grader.check("q3_b")

q3_b results: All test cases passed!

c. what are the data types of the columns? Store your answer in the `coral_div_types`.

In [9]:
coral_div.dtypes

PU_ID                    int64
PU_Lat                 float64
PU_Lon                 float64
Number_of_genera         int64
Country                 object
Ecoregion               object
Management              object
Habitat                 object
Observer                object
Depth                  float64
Coralcover               int64
SSTRateofRise          float64
PARmax                 float64
Calcite                float64
Dis_oxygen             float64
mean.waveNRJ           float64
Salinity_mean          float64
andrello_reef_value      int64
andrello_nutrients     float64
mean.npp               float64
TT_market_hrs          float64
TT_pop_hrs             float64
cumDHW                 float64
SST_Kurtosis           float64
SST_Median             float64
ChlorA_median          float64
andrello_sediments     float64
Current_vel_mean       float64
Diff_attenuation       float64
Grav_NP                float64
Grav_NC                float64
PH                     float64
SST_bimodality         float64
SST_Skewness           float64
ClimateStressModel     float64
Netflow                float64
Indegree               float64
Outdegree              float64
Retention              float64
min_yr                   int64
max_yr                   int64
no_replicates            int64
dtype: object

In [10]:
#c
coral_div_types = coral_div.dtypes

In [11]:
grader.check("q3_c")

q3_c results: All test cases passed!

d. display the first 8 rows with all the column names. For this one, you will need to udpate a `pandas` option (HINT: check the first discussion section). Store your answer in the `first_8_rows` variable.

In [12]:
coral_div.head(8)

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,...,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,...,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [13]:
#d
first_8_rows = coral_div.head(8)

In [14]:
# View the dataframe 
first_8_rows

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
0,7,39.076711,-5.490011,35,Tanzania,East African Coral Coast,UnfishedLow,Crest,Tim,11.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2019,2019,1
1,7,39.076711,-5.490011,22,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,2.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2010,2015,2
2,7,39.076711,-5.490011,25,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,4.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2015,2015,1
3,7,39.076711,-5.490011,26,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.0,...,0.462556,-0.128136,0.596375,0.144498,98.25,74.75,14.00,2016,2019,2
4,10,39.054253,-5.512514,27,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2010,2019,3
5,10,39.054253,-5.512514,29,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,1.5,...,0.461297,-0.134548,0.629000,0.011721,112.75,51.50,183.75,2015,2015,1
6,15,39.054253,-5.535017,19,Tanzania,East African Coral Coast,Restricted,Crest,Tim,8.0,...,0.461297,-0.134548,0.595600,0.011721,112.75,51.50,183.75,2019,2019,1
7,39,39.009337,-5.647518,28,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.0,...,0.464874,-0.158601,0.626000,-0.063087,96.50,40.75,35.75,2015,2019,3

In [15]:
grader.check("q3_d")

q3_d results: All test cases passed!

<!-- BEGIN QUESTION -->

e. Write code to find out some other inital information you are interested in.

In [16]:
coral_div.nunique()

PU_ID                  304
PU_Lat                 152
PU_Lon                 217
Number_of_genera        37
Country                 11
Ecoregion                6
Management               4
Habitat                  6
Observer                16
Depth                  111
Coralcover              46
SSTRateofRise          283
PARmax                 221
Calcite                219
Dis_oxygen             187
mean.waveNRJ           237
Salinity_mean          226
andrello_reef_value    139
andrello_nutrients     165
mean.npp               197
TT_market_hrs          129
TT_pop_hrs              51
cumDHW                 283
SST_Kurtosis           283
SST_Median             193
ChlorA_median          283
andrello_sediments     180
Current_vel_mean       224
Diff_attenuation       165
Grav_NP                168
Grav_NC                169
PH                      62
SST_bimodality         282
SST_Skewness           283
ClimateStressModel     297
Netflow                126
Indegree               110
Outdegree              106
Retention              109
min_yr                  19
max_yr                  19
no_replicates           12
dtype: int64

In [17]:
# e
coral_div.describe()

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Depth,Coralcover,SSTRateofRise,PARmax,Calcite,Dis_oxygen,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
count,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,...,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000,575.000000
mean,3536.620870,43.976240,-12.633028,20.182609,6.253192,38.340870,0.017559,55.558422,0.003622,4.684780,...,0.529946,-0.071522,0.549405,0.203586,51.882609,55.963043,91.107391,2013.165217,2013.923478,1.716522
std,2345.438008,6.549987,6.972048,6.568299,4.501193,10.586395,0.006552,2.118008,0.007026,0.108744,...,0.047659,0.127463,0.151452,0.344229,37.238322,27.701567,147.657638,4.693628,4.638243,1.524934
min,7.000000,32.878336,-27.011417,3.000000,0.500000,10.000000,-0.000463,48.774500,0.000058,4.373000,...,0.416042,-0.297088,0.081800,-0.576851,2.500000,10.500000,0.000000,1998.000000,1998.000000,1.000000
25%,1413.500000,39.413579,-20.006995,16.000000,2.000000,31.000000,0.015466,54.117250,0.000272,4.626000,...,0.488628,-0.168714,0.470100,-0.023227,21.250000,35.625000,11.750000,2009.000000,2010.000000,1.000000
50%,4002.000000,40.671221,-12.827030,20.000000,5.000000,39.000000,0.019233,55.523998,0.000906,4.711000,...,0.547940,-0.095642,0.579325,0.233054,43.500000,54.250000,47.750000,2014.000000,2015.000000,1.000000
75%,5182.000000,48.497793,-5.523765,24.000000,9.500000,45.000000,0.021978,57.133999,0.002866,4.755500,...,0.570981,0.018935,0.656300,0.509071,81.250000,77.000000,109.000000,2016.000000,2018.000000,2.000000
max,11683.000000,57.806585,-1.745137,40.000000,29.000000,60.000000,0.027391,62.193001,0.055976,4.850250,...,0.598189,0.304314,0.813600,0.815635,146.750000,136.000000,1561.500000,2022.000000,2022.000000,19.000000

In [18]:
coral_div.isna().sum() #Count missing values in each column

PU_ID                   0
PU_Lat                  0
PU_Lon                  0
Number_of_genera        0
Country                 0
Ecoregion               0
Management              0
Habitat                45
Observer                0
Depth                   0
Coralcover              0
SSTRateofRise           0
PARmax                  0
Calcite                 0
Dis_oxygen              0
mean.waveNRJ            0
Salinity_mean           0
andrello_reef_value     0
andrello_nutrients      0
mean.npp                0
TT_market_hrs           0
TT_pop_hrs              0
cumDHW                  0
SST_Kurtosis            0
SST_Median              0
ChlorA_median           0
andrello_sediments      0
Current_vel_mean        8
Diff_attenuation        0
Grav_NP                 0
Grav_NC                 0
PH                      0
SST_bimodality          0
SST_Skewness            0
ClimateStressModel      0
Netflow                 0
Indegree                0
Outdegree               0
Retention               0
min_yr                  0
max_yr                  0
no_replicates           0
dtype: int64

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 4

Some of the columns have data type `int64` and some have data type `float64`. What is the difference between these `int64` and `float64`?

An integer is a whole number (ex: 1,7,10) and floats include values that are decimals (ex: 0.01, 1.00, 5.05).

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 5

The `Country` column indicates the country where the coral reef is located. Explain, in your own words, what is the ouput of `coral_div['Country']` and `coral_div['Country'].unique()`.

In [19]:
coral_div['Country']

0          Tanzania
1          Tanzania
2          Tanzania
3          Tanzania
4          Tanzania
           ...
570    South Africa
571    South Africa
572    South Africa
573    South Africa
574    South Africa
Name: Country, Length: 575, dtype: object

coral_div['Country'] will output the the column named 'Country' in the data frame coral_div. It will show you the first five and last five rows along with information such as length and dtype.

In [20]:
coral_div['Country'].unique()

array(['Tanzania', 'Mozambique', 'Kenya', 'Reunion', 'Comoros', 'Mayotte',
       'French Southern Territories', 'Madagascar', 'Seychelles',
       'South Africa', 'Mauritius'], dtype=object)

coral_div['Country'].unique() will ouput the amount of unique values in the column named 'Country' in the data frame coral_div.

<!-- END QUESTION -->

## 6

Check the dataset's [metadata file README_md.doc](https://knb.ecoinformatics.org/view/doi:10.5063/F1K35S3H) to find which column has information about who made an observation. How many observers collected this data? HINT: Check this [method for `pandas.DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nunique.html). Store your answer in the `unique_observers` variable.

In [21]:
coral_div['Observer'].nunique()

16

In [22]:
unique_observers = 16

In [23]:
grader.check("q6")

q6 results: All test cases passed!

## 7

The `Coralcover` column indicates the percent of hard coral cover in each 6 km reef cell surveyed.

<!-- BEGIN QUESTION -->

a)  Describe, in detail,  what kind of object `coral_div['Coralcover']>= 50` is.

In [24]:
coral_div['Coralcover']>= 50

0      False
1      False
2      False
3      False
4      False
       ...
570    False
571    False
572    False
573    False
574    False
Name: Coralcover, Length: 575, dtype: bool

`coral_div['Coralcover']>= 50` is a boolean, the code above is a condition that will output true or false.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

b) What data is `coral_div[coral_div['Coralcover'] >= 50]` selecting?

In [25]:
coral_div[coral_div['Coralcover'] >= 50]

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
39,220,39.233916,-6.658981,17,Tanzania,East African Coral Coast,UnfishedLow,Slope,Nyawira,3.000000,...,0.527900,-0.171423,0.62130,-0.443779,127.50,62.25,204.75,2016,2016,1
40,220,39.233916,-6.658981,19,Tanzania,East African Coral Coast,UnfishedLow,Slope,Tim,2.833333,...,0.527900,-0.171423,0.62130,-0.443779,127.50,62.25,204.75,2012,2019,3
41,221,39.256374,-6.658981,25,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,10.000000,...,0.526911,-0.169093,0.52760,-0.443779,127.50,62.25,204.75,2016,2016,1
42,221,39.256374,-6.658981,19,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Tim,10.000000,...,0.526911,-0.169093,0.52760,-0.443779,127.50,62.25,204.75,2016,2016,1
43,221,39.256374,-6.658981,12,Tanzania,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,3.000000,...,0.526911,-0.169093,0.52760,-0.443779,127.50,62.25,204.75,2016,2016,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303,4039,48.082322,-13.553193,27,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,Arielle,6.733333,...,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2017,2019,3
304,4039,48.082322,-13.553193,20,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,D'Agata,6.000000,...,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2016,2016,2
305,4039,48.082322,-13.553193,21,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,Julien,5.000000,...,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2016,2016,1
306,4039,48.082322,-13.553193,33,Madagascar,Western and Northern Madagascar,UnfishedLow,Slope,Nyawira,5.000000,...,0.566251,-0.271831,0.72960,0.670117,12.50,29.00,62.50,2015,2015,1
514,6064,40.603847,-12.496246,30,Mozambique,East African Coral Coast,UnfishedLow,Lagoon/Back reef,Nyawira,8.000000,...,0.529942,-0.145626,0.68105,0.116857,54.75,54.25,126.50,2015,2015,1

coral_div[coral_div['Coralcover'] >= 50] is selecting all rows that have a value of 50 or greater in 'Coralcover' column.

<!-- END QUESTION -->

## 8

Use code to find if there are there any sites with a 30% coral cover in Tanzania. Store your answer in the `coral_cover` variable.

In [26]:
coral_div[(coral_div['Coralcover'] == 30) & (coral_div['Country'] == 'Tanzania')]

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
63,693,39.391121,-5.782490,10,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,5.000000,...,0.490512,-0.101724,0.655600,-0.309514,77.00,65.25,147.50,2018,2018,2
64,697,39.391121,-5.804983,22,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.166667,...,0.490769,-0.100365,0.683050,-0.309514,77.00,65.25,147.50,2010,2018,3
341,4294,39.211458,-4.814515,37,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,...,0.451293,-0.048992,0.608900,0.514920,46.00,49.50,82.75,2018,2018,1
342,4299,39.233916,-4.837043,26,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,12.500000,...,0.451293,-0.048992,0.601725,0.514920,46.00,49.50,82.75,2018,2018,2
343,4302,39.211458,-4.859570,31,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,7.000000,...,0.452402,-0.050477,0.595200,0.514920,46.00,49.50,82.75,2018,2018,1
344,4303,39.301290,-4.859570,23,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,...,0.453806,-0.048007,0.602300,0.514920,46.00,49.50,82.75,2018,2018,1
377,4906,39.660616,-4.972195,33,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.000000,...,0.488396,-0.074229,0.671900,0.156359,66.75,41.75,38.00,2013,2013,2
388,5049,39.615700,-5.490011,14,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,4.000000,...,0.489921,-0.109523,0.657000,-0.328399,93.25,57.25,650.25,2018,2018,1
389,5050,39.638158,-5.490011,18,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,6.000000,...,0.489921,-0.109523,0.618825,-0.328399,93.25,57.25,650.25,2018,2018,1

In [27]:
coral_cover = coral_div[(coral_div['Coralcover'] == 30) & (coral_div['Country'] == 'Tanzania')]

In [28]:
# View the dataframe
coral_cover

,PU_ID,PU_Lat,PU_Lon,Number_of_genera,Country,Ecoregion,Management,Habitat,Observer,Depth,...,SST_bimodality,SST_Skewness,ClimateStressModel,Netflow,Indegree,Outdegree,Retention,min_yr,max_yr,no_replicates
63,693,39.391121,-5.782490,10,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,5.000000,...,0.490512,-0.101724,0.655600,-0.309514,77.00,65.25,147.50,2018,2018,2
64,697,39.391121,-5.804983,22,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.166667,...,0.490769,-0.100365,0.683050,-0.309514,77.00,65.25,147.50,2010,2018,3
341,4294,39.211458,-4.814515,37,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,...,0.451293,-0.048992,0.608900,0.514920,46.00,49.50,82.75,2018,2018,1
342,4299,39.233916,-4.837043,26,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,12.500000,...,0.451293,-0.048992,0.601725,0.514920,46.00,49.50,82.75,2018,2018,2
343,4302,39.211458,-4.859570,31,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,7.000000,...,0.452402,-0.050477,0.595200,0.514920,46.00,49.50,82.75,2018,2018,1
344,4303,39.301290,-4.859570,23,Tanzania,East African Coral Coast,Fished,Slope,Nyawira,11.000000,...,0.453806,-0.048007,0.602300,0.514920,46.00,49.50,82.75,2018,2018,1
377,4906,39.660616,-4.972195,33,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,9.000000,...,0.488396,-0.074229,0.671900,0.156359,66.75,41.75,38.00,2013,2013,2
388,5049,39.615700,-5.490011,14,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,4.000000,...,0.489921,-0.109523,0.657000,-0.328399,93.25,57.25,650.25,2018,2018,1
389,5050,39.638158,-5.490011,18,Tanzania,East African Coral Coast,Fished,Lagoon/Back reef,Nyawira,6.000000,...,0.489921,-0.109523,0.618825,-0.328399,93.25,57.25,650.25,2018,2018,1

In [29]:
grader.check("q8")

q8 results: All test cases passed!

## 9

We are interested in looking at the PH of sea water (`PH` column),  mean salinity (`Salinity_mean` column), and depth of survey location in meters (`Depth` column). Subset the data frame by selecting only these column. Store your answer in the `filtered_data` variable

In [45]:
coral_div[['PH',"Salinity_mean",'Depth']]

         PH  Salinity_mean  Depth
0    8.2175      35.167646  11.00
1    8.2175      35.167646   2.00
2    8.2175      35.167646   4.00
3    8.2175      35.167646   3.00
4    8.2180      35.102688   1.50
..      ...            ...    ...
570  8.2400      35.301208  15.50
571  8.2400      35.301208  12.00
572  8.2400      35.301208  12.60
573  8.2400      35.301208  13.00
574  8.2400      35.301208  13.47

[575 rows x 3 columns]

In [46]:
filtered_data = coral_div[['PH',"Salinity_mean",'Depth']]

In [47]:
# View the dataframe
filtered_data.head()

       PH  Salinity_mean  Depth
0  8.2175      35.167646   11.0
1  8.2175      35.167646    2.0
2  8.2175      35.167646    4.0
3  8.2175      35.167646    3.0
4  8.2180      35.102688    1.5

In [48]:
grader.check("q9")

q9 results: All test cases passed!

## 10
The `max_yr` column indicates the year of last sampling at a given site. Select the PH, salinity, and depth for sites where sampling ended in 2017. Store your answer in the `sampling_2017` variable. `Sampling_2017` should include the following columns in the following order: ` PH, Salinity_mean, Depth, max_yr`.

In [52]:
sampling_2017 = coral_div[['PH',"Salinity_mean",'Depth', 'max_yr']]

KeyError: '[False] not in index'

In [ ]:
# View the dataframe 
sampling_2017

In [ ]:
grader.check("q10")

## 11
Use `iloc` to select rows 95 through 100 (including 100) in the 17th, 20th, and 28th columns and assign these values to a new variable called `subset`. View the new `subset` dataframe.

HINT: the ouput columns should be `Salinity_mean`, `mean.npp` and `Current_vel_mean` (in that order!).

In [60]:
coral_div.iloc[95:101,[16,19,27]]

     andrello_reef_value  TT_market_hrs  Diff_attenuation
95                  1026       1.766667             0.197
96                  1222       0.450000             0.105
97                  1222       0.450000             0.090
98                  1222       0.450000             0.090
99                  1611       0.783333             0.075
100                 1611       0.783333             0.075

In [64]:
subset = coral_div.iloc[95:101,[16,19,27]]

In [65]:
# View the dataframe
subset

     Salinity_mean     mean.npp  Current_vel_mean
95       35.201630  1365.146729          0.878417
96       35.204185  1117.635010          0.839372
97       35.234774  1105.270142          0.685955
98       35.234774  1105.270142          0.685955
99       35.250068  1082.196411               NaN
100      35.250068  1082.196411               NaN

In [66]:
grader.check("q11")

q11 results: All test cases passed!

<!-- BEGIN QUESTION -->

## 12 

Run `subset.isna()`. Explain what this code does and what the output represents.

In [70]:
subset.isna()

     Salinity_mean  mean.npp  Current_vel_mean
95           False     False             False
96           False     False             False
97           False     False             False
98           False     False             False
99           False     False              True
100          False     False              True

subset.isna()that checks if here is a value in every row and colum, it will return TRUE if the value is NaN and FALSE if there is a value.

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## 13
Run `subset.isna().any()`. Explain in your own words what this code does and what the output represents. HINT: check the [documentation of `pandas.Sries.any`](https://pandas.pydata.org/docs/reference/api/pandas.Series.any.html).

In [71]:
subset.isna().any()

Salinity_mean       False
mean.npp            False
Current_vel_mean     True
dtype: bool

.isna().any() checks if there are any missing values in all rows in each column, it will return TRUE if the value is NaNs in the column and FALSE if the column does not contain missing values.

<!-- END QUESTION -->

## 14 

Select the rows in `subset` that have NA in the `Current_vel_mean` column. Store your answer in the `subset_na` variable.

In [ ]:
subset_na = ...

In [ ]:
# View the dataframe 
subset_na

In [ ]:
grader.check("q14")

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [ ]:
grader.check_all()